name: Build and Deploy One Of Us

on:
  push:
    branches: [main, master]
    paths-ignore:
      - '.github/**'
      - '**.md'
    tags: ["*-v*"]
  workflow_dispatch:
    inputs:
      env:
        type: choice
        description: Target environment
        required: false
        options:
          - dev
          - stg
          - prod
      deploy_backend:
        type: boolean
        description: Deploy backend
        default: true
      deploy_frontend:
        type: boolean
        description: Deploy frontend
        default: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  packages: write
  actions: write
  id-token: write

jobs:
  deploy_backend:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      app: one-of-us
      component: backend
      env: ${{ inputs.env }}
      dockerfile: backend/Dockerfile
      context: backend
      paths_filter: |
        backend/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}

  deploy_frontend:
    uses: gear-ops/actions/.github/workflows/build-deploy.yaml@main
    with:
      argocd_server: ${{ vars.ARGOCD_SERVER }}
      vault_server: ${{ vars.VAULT_SERVER }}
      app: one-of-us
      component: frontend
      env: ${{ inputs.env }}
      dockerfile: frontend/Dockerfile
      context: frontend
      paths_filter: |
        frontend/**
    secrets:
      WORKLOADS_REPO_TOKEN: ${{ secrets.WORKLOADS_REPO_TOKEN }}
      ARGOCD_TOKEN:         ${{ secrets.ARGOCD_TOKEN }}
